// Generated by CoffeeScript 2.5.1
var moment;

moment = require("moment");

exports._add = function(mult, inc, m) {
  return m.clone().add(mult, inc);
};

exports._addDurationToMoment = function(m, duration) {
  return m.clone().add(duration);
};

exports._addDurations = function(d1, d2) {
  return d1.clone().add(d2);
};

exports._subtract = function(mult, inc, m) {
  return m.clone().subtract(mult, inc);
};

exports._duration = function(mult, inc) {
  return moment.duration(mult, inc);
};

exports._fromUTC = function(utc) {
  return moment.utc(utc);
};

exports._fromDate = function(date) {
  return moment.utc(date);
};

exports._isAfter = function(m1, m2) {
  return m1.isAfter(m2);
};

exports._isBefore = function(m1, m2) {
  return m1.isBefore(m2);
};

exports._isSame = function(m1, m2) {
  return m1.isSame(m2);
};

exports._now = function() {
  return moment();
};

exports._diff = function(m1, m2) {
  return moment.duration(m1.diff(m2));
};

exports._seconds = function(d) {
  return d.seconds();
};

exports._format = function(m) {
  return m.format();
};
